#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
nitrogen --restore &
picom &

xrandr --output HDMI-0 --mode 1920x1080 --rate 119.98 --left-of DP-2 --output DP-2 --mode 1920x1080 --rate 165.00 --primary &

setxkbmap se &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config focused_border_color "#A2A2A2"
bspc config normal_border_color  "#202020"
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=tiling follow=on
bspc rule -a Spotify desktop='^6' state=tiling follow=on
